version: '3.9'

services:
  yolo-cuda:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yolo_cuda
    privileged: true
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - .:/app
      - /usr/bin/tegrastats:/usr/bin/tegrastats:ro
      - ./Datasets:/Datasets:rw   
     # - ./outputs:/app/outputs
      - ./runs:/ultralytics/runs
      - ./runs:/root/Ultralytics/runs
    working_dir: /app 
   # restart: unless-stopped
    command: sh -c "python3 yolo.py --eval --batch_size 1 --device "cuda" > results.txt 2>&1"
    tty: true
